### ISSUE TITLE
Regenerate adif_pb2

### ISSUE THREAD

**Issue by pepassaco** [k0swe/adif-json-protobuf#57]
I am getting the following error when trying to execute the demo: 

```
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
```

Hope it has an easy fix by updating the adif_pb2 file

**Comment by xylo04** [comment]
In order to update the adif_pb2 file I would have needed to upgrade my local `protoc`. Since I installed that via `apt`, it's pretty far out of date. Rather than experimenting with different versions of `protoc`, I've depended on a slightly older version of the python protobuf library.
